### ISSUE TITLE
about 1-1-0g etc.

### ISSUE THREAD

**Issue by guoliangchao** [cvg/VP-Estimation-with-Prior-Gravity#6]
Hello, I would like to ask you a question about the paper. Figure 2 in the paper mentions 2-0-0g,0-1-1g,1-1-0g. What do the numbers in each of these names mean? Is 1g the direction of gravity known? Does 0g mean that the direction of gravity is unknown? And is the vertical direction and the gravitational direction mentioned many times in the paper the same thing? Despite the explanation in the paper, I am still confused and do not understand the meaning of this name.

**Comment by rpautrat** [comment]
Hi, sorry if the figure and caption were not self explanatory enough. The three numbers indicates the minimal number of lines associated to each vanishing point (VP) to sample for each solver. In the figure, the first number corresponds to the red VP, the second to the green VP, and the last number corresponds to the blue VP (the vertical one). The g suffix simply means that the solver is assuming that it has access to the prior gravity, and is appended to the third number because this is the one associated to the vertical VP. Gravity and vertical direction are the same, indeed.

So for example, the 0-1-1g solver requires 0 lines associated to the red VP, 1 line to the green VP, and 1 line associated to the vertical blue VP.

I hope this clarifies the figure.

**Comment by guoliangchao** [comment]
> Hi, sorry if the figure and caption were not self explanatory enough. The three numbers indicates the minimal number of lines associated to each vanishing point (VP) to sample for each solver. In the figure, the first number corresponds to the red VP, the second to the green VP, and the last number corresponds to the blue VP (the vertical one). The g suffix simply means that the solver is assuming that it has access to the prior gravity, and is appended to the third number because this is the one associated to the vertical VP. Gravity and vertical direction are the same, indeed.
> 
> So for example, the 0-1-1g solver requires 0 lines associated to the red VP, 1 line to the green VP, and 1 line associated to the vertical blue VP.
> 
> I hope this clarifies the figure.

Thank you very much.By your interpretation, I have solved this issue.
